# Generated by Django 5.2.15 on 2026-06-11 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notif_type",
                    models.CharField(
                        choices=[
                            ("submission_submitted", "Pengajuan Diterima"),
                            ("stage_advanced", "Tahap Berlanjut"),
                            ("revision_requested", "Revisi Diminta"),
                            ("submission_approved", "Izin Disetujui"),
                            ("submission_rejected", "Izin Ditolak"),
                            ("permit_published", "Izin Diterbitkan"),
                            ("sla_at_risk", "SLA Mendekati Batas"),
                            ("sla_breached", "SLA Terlampaui"),
                            ("visit_scheduled", "Kunjungan Dijadwalkan"),
                            ("general", "Umum"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("submission_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("action_url", models.CharField(blank=True, max_length=500)),
                ("email_sent", models.BooleanField(default=False)),
                ("whatsapp_sent", models.BooleanField(default=False)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"], name="notificatio_recipie_4e3567_idx"
                    )
                ],
            },
        ),
    ]
