# Generated by Django 5.2.15 on 2026-06-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("submission_submitted", "Pengajuan Diterima"),
                    ("stage_advanced", "Tahap Berlanjut"),
                    ("revision_requested", "Revisi Diminta"),
                    ("submission_approved", "Izin Disetujui"),
                    ("submission_rejected", "Izin Ditolak"),
                    ("permit_published", "Izin Diterbitkan"),
                    ("sla_at_risk", "SLA Mendekati Batas"),
                    ("sla_breached", "SLA Terlampaui"),
                    ("visit_scheduled", "Kunjungan Dijadwalkan"),
                    ("antrean_available", "Antrean Tersedia"),
                    ("antrean_ticket_taken", "Nomor Antrean Diterima"),
                    ("antrean_almost_turn", "Antrean Hampir Tiba"),
                    ("antrean_called", "Dipanggil ke Loket"),
                    ("antrean_no_show", "Nomor Antrean Hangus"),
                    ("general", "Umum"),
                ],
                max_length=40,
            ),
        ),
    ]
