# Generated by Django 5.2.15 on 2026-06-29 10:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engine", "0005_formfield_conditional_field_key_and_more"),
        ("reference", "0003_kedeputian_direktorat"),
        ("submissions", "0004_submission_assigned_at_submission_assigned_to_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Instansi",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=300)),
                ("short_name", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "direktorat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mpp_instansi",
                        to="reference.direktorat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instansi MPP",
                "verbose_name_plural": "Instansi MPP",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Layanan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=120)),
                ("name", models.CharField(max_length=300)),
                (
                    "category",
                    models.CharField(
                        choices=[("cepat", "Cepat"), ("sedang", "Sedang"), ("lama", "Lama")],
                        default="sedang",
                        max_length=10,
                    ),
                ),
                (
                    "avg_minutes",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Rata-rata menit/layanan — basis estimasi waktu tunggu.",
                    ),
                ),
                (
                    "online_ratio",
                    models.DecimalField(decimal_places=2, default=Decimal("0.60"), max_digits=3),
                ),
                ("priority_ratio_n", models.PositiveSmallIntegerField(default=3)),
                ("daily_quota", models.PositiveIntegerField(blank=True, null=True)),
                ("recall_max", models.PositiveSmallIntegerField(default=2)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "instansi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="layanan",
                        to="antrean.instansi",
                    ),
                ),
                (
                    "permit_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="antrean_layanan",
                        to="engine.permittype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Layanan Antrean",
                "verbose_name_plural": "Layanan Antrean",
                "ordering": ["instansi", "order", "name"],
                "unique_together": {("instansi", "key")},
            },
        ),
        migrations.CreateModel(
            name="Loket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(help_text="Display label, e.g. 'Loket 3'.", max_length=20),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("is_open", models.BooleanField(default=False)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operating_loket",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instansi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loket",
                        to="antrean.instansi",
                    ),
                ),
                (
                    "layanan",
                    models.ManyToManyField(blank=True, related_name="loket", to="antrean.layanan"),
                ),
            ],
            options={
                "verbose_name": "Loket",
                "verbose_name_plural": "Loket",
                "ordering": ["instansi", "code"],
                "unique_together": {("instansi", "code")},
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("service_date", models.DateField(db_index=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("online", "Online"), ("walkin", "Walk-in")], max_length=10
                    ),
                ),
                (
                    "number",
                    models.CharField(help_text="Display label, e.g. 'A-012'.", max_length=20),
                ),
                (
                    "seq",
                    models.PositiveIntegerField(
                        help_text="Raw per-(layanan, service_date) sequence."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Dipesan"),
                            ("checked_in", "Check-in"),
                            ("in_pool", "Dalam Kolam Panggil"),
                            ("called", "Dipanggil"),
                            ("serving", "Dilayani"),
                            ("served", "Selesai"),
                            ("no_show", "Tidak Hadir"),
                            ("expired", "Kedaluwarsa"),
                            ("cancelled", "Dibatalkan"),
                        ],
                        db_index=True,
                        default="reserved",
                        max_length=12,
                    ),
                ),
                ("is_priority", models.BooleanField(default=False)),
                ("taken_at", models.DateTimeField()),
                ("estimated_call_at", models.DateTimeField(blank=True, null=True)),
                ("checkin_at", models.DateTimeField(blank=True, null=True)),
                ("checkin_deadline", models.DateTimeField(blank=True, null=True)),
                ("called_at", models.DateTimeField(blank=True, null=True)),
                ("recall_count", models.PositiveSmallIntegerField(default=0)),
                ("serving_at", models.DateTimeField(blank=True, null=True)),
                ("served_at", models.DateTimeField(blank=True, null=True)),
                ("is_demoted", models.BooleanField(default=False)),
                ("last_notified_ahead", models.PositiveIntegerField(blank=True, null=True)),
                ("holder_name", models.CharField(blank=True, max_length=200)),
                ("holder_phone", models.CharField(blank=True, max_length=20)),
                ("triage_note", models.TextField(blank=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="antrean_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "layanan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="antrean.layanan",
                    ),
                ),
                (
                    "loket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="antrean.loket",
                    ),
                ),
                (
                    "served_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="served_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="antrean_tickets",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tiket Antrean",
                "verbose_name_plural": "Tiket Antrean",
                "ordering": ["service_date", "seq"],
            },
        ),
        migrations.CreateModel(
            name="TicketEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("take", "Ambil Nomor"),
                            ("check_in", "Check-in"),
                            ("demote", "Turun Posisi"),
                            ("call", "Dipanggil"),
                            ("recall", "Panggil Ulang"),
                            ("serve", "Mulai Dilayani"),
                            ("complete", "Selesai Dilayani"),
                            ("no_show", "Tidak Hadir"),
                            ("expire", "Kedaluwarsa"),
                            ("cancel", "Dibatalkan"),
                            ("retriage", "Koreksi Layanan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=12)),
                ("to_status", models.CharField(blank=True, max_length=12)),
                ("notes", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="antrean_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="antrean.loket",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="antrean.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CounterStaffAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role_scope",
                    models.CharField(
                        choices=[("operator", "Petugas Loket"), ("supervisor", "Supervisor MPP")],
                        default="operator",
                        max_length=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="counter_assignments_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counter_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instansi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_assignments",
                        to="antrean.instansi",
                    ),
                ),
                (
                    "loket",
                    models.ForeignKey(
                        blank=True,
                        help_text="Blank = any loket within the instansi.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_assignments",
                        to="antrean.loket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Penugasan Petugas Loket",
                "verbose_name_plural": "Penugasan Petugas Loket",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="antrean_cou_user_id_f12f39_idx"
                    )
                ],
                "unique_together": {("user", "instansi", "loket", "role_scope")},
            },
        ),
        migrations.CreateModel(
            name="QueueParameter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        help_text="e.g. checkin_window_min, noshow_grace_min, operating_open, operating_close, cutoff_min, position_notify_threshold",
                        max_length=60,
                    ),
                ),
                ("value", models.CharField(max_length=120)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("int", "Integer"),
                            ("decimal", "Decimal"),
                            ("time", "Time (HH:MM)"),
                            ("bool", "Boolean"),
                        ],
                        default="int",
                        max_length=10,
                    ),
                ),
                (
                    "layanan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="antrean.layanan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parameter Antrean",
                "verbose_name_plural": "Parameter Antrean",
                "ordering": ["layanan", "key"],
                "unique_together": {("layanan", "key")},
            },
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["layanan", "service_date", "status"], name="antrean_tic_layanan_3771b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["status", "estimated_call_at"], name="antrean_tic_status_f7a1de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["applicant", "status"], name="antrean_tic_applica_1a403f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["submission"], name="antrean_tic_submiss_1becd3_idx"),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("layanan", "service_date", "seq"), name="uniq_ticket_seq_per_service_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ("reserved", "checked_in", "in_pool", "called", "serving"))
                ),
                fields=("layanan", "service_date", "applicant"),
                name="uniq_active_ticket_per_service_day",
            ),
        ),
    ]
