# Generated by Django 5.2.15 on 2026-07-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("antrean", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ticket",
            name="antrean_tic_submiss_1becd3_idx",
        ),
        migrations.RemoveField(
            model_name="layanan",
            name="permit_type",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="submission",
        ),
    ]
