# Generated by Django 5.2.15 on 2026-07-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("antrean", "0002_remove_ticket_antrean_tic_submiss_1becd3_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instansi",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="mpp/tenants/"),
        ),
        migrations.AddField(
            model_name="instansi",
            name="owner_type",
            field=models.CharField(
                choices=[("oikn", "Otorita IKN"), ("external", "Instansi Eksternal")],
                default="oikn",
                max_length=10,
            ),
        ),
    ]
