# Generated by Django 5.2.15 on 2026-07-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("antrean", "0003_instansi_logo_instansi_owner_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="holder_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="ticket",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="mpp/tickets/"),
        ),
    ]
