# Generated by Django 5.2.15 on 2026-07-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("antrean", "0004_ticket_holder_email_ticket_pdf_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counterstaffassignment",
            name="role_scope",
            field=models.CharField(
                choices=[("loket_operator", "Petugas Loket"), ("tenant_admin", "Admin Tenant")],
                default="loket_operator",
                max_length=16,
            ),
        ),
    ]
