# Generated by Django 5.2.15 on 2026-07-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("antrean", "0006_rename_mpp_roles_and_scopes"),
    ]

    operations = [
        migrations.AddField(
            model_name="instansi",
            name="break_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instansi",
            name="break_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instansi",
            name="operating_close",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instansi",
            name="operating_open",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
