# Generated by Django 5.2.15 on 2026-06-11 10:14

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sektor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_catchall",
                    models.BooleanField(
                        default=False, help_text="True for the 'Lainnya' escape-hatch sektor"
                    ),
                ),
                ("pengampu", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Sektor",
                "verbose_name_plural": "Sektor",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PermitType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("is_berusaha", models.BooleanField(default=False)),
                (
                    "oss_covered",
                    models.BooleanField(
                        default=False,
                        help_text="If True route applicant to OSS — do NOT reimplement",
                    ),
                ),
                ("oss_deeplink", models.URLField(blank=True)),
                ("sla_days", models.PositiveSmallIntegerField(help_text="Jangka Waktu Pelayanan")),
                ("product_name", models.CharField(blank=True, max_length=300)),
                (
                    "legal_basis",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list, size=None
                    ),
                ),
                ("fee_description", models.TextField(blank=True)),
                ("complaint_info", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=False)),
                ("schema_version", models.PositiveIntegerField(default=1)),
                (
                    "sektor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="permit_types",
                        to="engine.sektor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permit Type",
                "verbose_name_plural": "Permit Types",
                "ordering": ["sektor__order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=120)),
                ("label", models.CharField(max_length=300)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Teks"),
                            ("textarea", "Teks Panjang"),
                            ("number", "Angka"),
                            ("date", "Tanggal"),
                            ("select", "Pilihan Tunggal"),
                            ("multiselect", "Pilihan Ganda"),
                            ("file", "File"),
                            ("nik", "NIK"),
                            ("npwp", "NPWP"),
                            ("phone", "Nomor Telepon"),
                            ("email", "Email"),
                            ("geo", "Koordinat"),
                            ("map_point", "Titik Peta"),
                        ],
                        max_length=30,
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveSmallIntegerField()),
                ("required", models.BooleanField(default=True)),
                ("validation_json", models.JSONField(default=dict)),
                ("options_json", models.JSONField(default=list)),
                ("prefill_from_profile", models.BooleanField(default=False)),
                ("help_text_field", models.TextField(blank=True)),
                ("placeholder", models.CharField(blank=True, max_length=300)),
                (
                    "permit_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_fields",
                        to="engine.permittype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Field",
                "verbose_name_plural": "Form Fields",
                "ordering": ["permit_type", "order"],
                "unique_together": {("permit_type", "key")},
            },
        ),
        migrations.CreateModel(
            name="DocumentRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=120)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "allowed_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        default=list,
                        help_text="e.g. ['pdf','jpg','png']",
                        size=None,
                    ),
                ),
                ("max_bytes", models.PositiveBigIntegerField(default=5242880)),
                ("required", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("conditional_field_key", models.CharField(blank=True, max_length=120)),
                ("conditional_field_value", models.CharField(blank=True, max_length=300)),
                (
                    "permit_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doc_requirements",
                        to="engine.permittype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Requirement",
                "verbose_name_plural": "Document Requirements",
                "ordering": ["permit_type", "order"],
                "unique_together": {("permit_type", "key")},
            },
        ),
        migrations.CreateModel(
            name="PermitTypeVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                ("snapshot", models.JSONField()),
                (
                    "permit_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="engine.permittype",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "unique_together": {("permit_type", "version")},
            },
        ),
        migrations.CreateModel(
            name="WorkflowStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=120)),
                ("order", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=200)),
                (
                    "stage_type",
                    models.CharField(
                        choices=[
                            ("verification", "Verifikasi"),
                            ("payment", "Pembayaran"),
                            ("external", "Proses Eksternal"),
                            ("publish", "Penerbitan"),
                            ("collection", "Pengambilan"),
                        ],
                        max_length=30,
                    ),
                ),
                ("actor_role", models.CharField(blank=True, max_length=200)),
                ("sla_hours", models.PositiveSmallIntegerField(default=0)),
                ("requires_site_visit", models.BooleanField(default=False)),
                (
                    "allowed_actions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        default=list,
                        help_text="e.g. ['approve','revise','reject','generate','sign']",
                        size=None,
                    ),
                ),
                ("is_terminal", models.BooleanField(default=False)),
                ("instructions", models.TextField(blank=True)),
                (
                    "permit_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="engine.permittype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Stage",
                "verbose_name_plural": "Workflow Stages",
                "ordering": ["permit_type", "order"],
                "unique_together": {("permit_type", "key"), ("permit_type", "order")},
            },
        ),
    ]
