# Generated by Django 5.2.15 on 2026-06-22 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0001_initial"),
        ("reference", "0003_kedeputian_direktorat"),
    ]

    operations = [
        migrations.AddField(
            model_name="sektor",
            name="pengampu_direktorat",
            field=models.ForeignKey(
                blank=True,
                help_text="Direktorat OIKN yang bertanggung jawab atas sektor ini",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pengampu_sektor",
                to="reference.direktorat",
            ),
        ),
    ]
