# Generated by Django 5.2.15 on 2026-06-26 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0002_sektor_pengampu_direktorat"),
        ("reference", "0003_kedeputian_direktorat"),
    ]

    operations = [
        migrations.AddField(
            model_name="sektor",
            name="direktorats",
            field=models.ManyToManyField(
                blank=True,
                help_text="Direktorat OIKN yang mengampu sektor ini (boleh lebih dari satu)",
                related_name="sektors",
                to="reference.direktorat",
            ),
        ),
        migrations.AlterField(
            model_name="sektor",
            name="pengampu",
            field=models.CharField(
                blank=True, help_text="Legacy free-text pengampu (fallback display)", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="sektor",
            name="pengampu_direktorat",
            field=models.ForeignKey(
                blank=True,
                help_text="Legacy single direktorat — superseded by direktorats (M2M)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pengampu_sektor",
                to="reference.direktorat",
            ),
        ),
    ]
