# Generated by Django 5.2.15 on 2026-06-26 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0004_backfill_sektor_direktorats"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="formfield",
            name="conditional_field_key",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="formfield",
            name="conditional_field_value",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="permittype",
            name="published_schema_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="permittypeversion",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permit_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="permittypeversion",
            name="note",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
