# Generated by Django 5.2.15 on 2026-06-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kblicode",
            name="lantara_izin_label",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="kblicode",
            name="pengampu",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="kblicode",
            name="sektor_oss_name",
            field=models.CharField(blank=True, help_text="SEKTOR (OSS)", max_length=500),
        ),
        migrations.AlterField(
            model_name="kblicode",
            name="verifier_sector",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
