# Generated by Django 5.2.15 on 2026-06-22 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0002_widen_kbli_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kedeputian",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=300)),
                ("short_name", models.CharField(blank=True, max_length=100)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Kedeputian",
                "verbose_name_plural": "Kedeputian",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Direktorat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=300)),
                ("short_name", models.CharField(blank=True, max_length=100)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "kedeputian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="direktorat_list",
                        to="reference.kedeputian",
                    ),
                ),
            ],
            options={
                "verbose_name": "Direktorat",
                "verbose_name_plural": "Direktorat",
                "ordering": ["kedeputian__order", "order", "name"],
            },
        ),
    ]
