# Generated by Django 5.2.15 on 2026-06-22 15:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("engine", "0002_sektor_pengampu_direktorat"),
        ("reference", "0003_kedeputian_direktorat"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="direktorat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_members",
                to="reference.direktorat",
            ),
        ),
        migrations.CreateModel(
            name="VerifierPermitAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "permit_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifier_assignments",
                        to="engine.permittype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permit_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="accounts_ve_user_id_9d7ae2_idx"
                    )
                ],
                "unique_together": {("user", "permit_type")},
            },
        ),
    ]
