# Generated by Django 5.2.15 on 2026-06-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_direktorat_verifierpermitassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="jabatan",
            field=models.CharField(
                blank=True,
                help_text="Job title from SSO (jabatan/unit_kerja claim)",
                max_length=255,
            ),
        ),
    ]
