# Generated by Django 5.2.15 on 2026-06-11 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engine", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference_number", models.CharField(blank=True, max_length=100, unique=True)),
                ("schema_version_snapshot", models.PositiveIntegerField(blank=True, null=True)),
                ("schema_snapshot", models.JSONField(blank=True, null=True)),
                ("form_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draf"),
                            ("submitted", "Diajukan"),
                            ("in_review", "Sedang Diverifikasi"),
                            ("revision", "Perlu Revisi"),
                            ("approved", "Disetujui"),
                            ("rejected", "Ditolak"),
                            ("publishing", "Penerbitan"),
                            ("collection", "Siap Diambil"),
                            ("collected", "Selesai"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("current_stage_key", models.CharField(blank=True, max_length=120)),
                ("current_stage_order", models.PositiveSmallIntegerField(default=0)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("sla_due_at", models.DateTimeField(blank=True, null=True)),
                ("stage_entered_at", models.DateTimeField(blank=True, null=True)),
                ("stage_sla_due_at", models.DateTimeField(blank=True, null=True)),
                ("is_sla_breached", models.BooleanField(default=False)),
                ("is_sla_at_risk", models.BooleanField(default=False)),
                ("rejection_reason", models.TextField(blank=True)),
                ("last_acted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_acted_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "permit_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="engine.permittype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stage_key", models.CharField(max_length=120)),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("scheduled_time", models.TimeField(blank=True, null=True)),
                (
                    "officers",
                    models.TextField(blank=True, help_text="Comma-separated officer names/NIPs"),
                ),
                ("findings", models.TextField(blank=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_visits",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submit", "Diajukan"),
                            ("advance", "Lanjut Tahap"),
                            ("approve", "Disetujui"),
                            ("revise", "Revisi Diminta"),
                            ("reject", "Ditolak"),
                            ("resubmit", "Revisi Dikirim"),
                            ("generate", "Draf Diterbitkan"),
                            ("sign", "Ditandatangani"),
                            ("publish", "Izin Diterbitkan"),
                            ("collect", "Diambil"),
                            ("visit_scheduled", "Kunjungan Dijadwalkan"),
                            ("visit_completed", "Kunjungan Selesai"),
                            ("comment", "Catatan"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_applicant_action", models.BooleanField(default=False)),
                ("from_stage_key", models.CharField(blank=True, max_length=120)),
                ("to_stage_key", models.CharField(blank=True, max_length=120)),
                ("from_status", models.CharField(blank=True, max_length=30)),
                ("to_status", models.CharField(blank=True, max_length=30)),
                ("notes", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_entries",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionIndex",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("applicant_email", models.EmailField(db_index=True, max_length=254)),
                ("applicant_name", models.CharField(max_length=200)),
                ("sektor_key", models.CharField(db_index=True, max_length=80)),
                ("sektor_name", models.CharField(max_length=200)),
                ("izin_key", models.CharField(db_index=True, max_length=120)),
                ("izin_name", models.CharField(max_length=300)),
                ("reference_number", models.CharField(db_index=True, max_length=100)),
                ("status", models.CharField(db_index=True, max_length=30)),
                ("current_stage_key", models.CharField(blank=True, max_length=120)),
                ("sla_due_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_sla_breached", models.BooleanField(db_index=True, default=False)),
                ("submitted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(db_index=True)),
                ("updated_at", models.DateTimeField()),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="index",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionRevisionField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("field_key", models.CharField(max_length=120)),
                ("is_doc_requirement", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revision_fields",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["applicant", "status"], name="submissions_applica_4a4678_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["permit_type", "status"], name="submissions_permit__3cdad8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["current_stage_key"], name="submissions_current_2e520f_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["sla_due_at"], name="submissions_sla_due_b93bcb_idx"),
        ),
        migrations.AddIndex(
            model_name="submissionindex",
            index=models.Index(
                fields=["sektor_key", "status"], name="submissions_sektor__b07453_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submissionindex",
            index=models.Index(
                fields=["izin_key", "status"], name="submissions_izin_ke_540a8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submissionindex",
            index=models.Index(
                fields=["is_sla_breached", "status"], name="submissions_is_sla__2bce99_idx"
            ),
        ),
    ]
