# Generated by Django 5.2.15 on 2026-06-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_revision_clarity"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitevisit",
            name="location",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
