# Generated by Django 5.2.15 on 2026-06-11 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requirement_key", models.CharField(db_index=True, max_length=120)),
                ("requirement_title", models.CharField(blank=True, max_length=300)),
                ("file", models.FileField(upload_to="submissions/documents/")),
                ("original_filename", models.CharField(max_length=300)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu Validasi"),
                            ("valid", "Valid"),
                            ("invalid", "Tidak Valid"),
                            ("infected", "Terdeteksi Malware"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("validation_error", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("revision_round", models.PositiveSmallIntegerField(default=0)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_documents",
                        to="submissions.submission",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["submission", "requirement_key"],
                        name="documents_u_submiss_9b49b3_idx",
                    ),
                    models.Index(
                        fields=["submission", "is_active"], name="documents_u_submiss_f59aa5_idx"
                    ),
                ],
            },
        ),
    ]
