# Generated by Django 5.2.15 on 2026-06-11 16:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("permits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TTERequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu"),
                            ("processing", "Diproses"),
                            ("signed", "Ditandatangani"),
                            ("failed", "Gagal"),
                            ("mock", "Mock (Simulasi)"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("bsre_transaction_id", models.CharField(blank=True, max_length=200)),
                ("signed_pdf_key", models.CharField(blank=True, max_length=500)),
                ("error_detail", models.TextField(blank=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("is_mock", models.BooleanField(default=False)),
                (
                    "permit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tte_request",
                        to="permits.issuedpermit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
