# Generated by Django 5.2.15 on 2026-06-11 10:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssuedPermit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "validation_uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "generation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu"),
                            ("draft", "Draf"),
                            ("signed", "Ditandatangani"),
                            ("published", "Diterbitkan"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("pdf_file", models.FileField(blank=True, null=True, upload_to="permits/pdf/")),
                (
                    "draft_pdf_file",
                    models.FileField(blank=True, null=True, upload_to="permits/drafts/"),
                ),
                ("signatory_name", models.CharField(blank=True, max_length=200)),
                ("signatory_title", models.CharField(blank=True, max_length=200)),
                ("signatory_nip", models.CharField(blank=True, max_length=30)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("copy_recipients", models.JSONField(default=list)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("generation_task_id", models.CharField(blank=True, max_length=100)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_permit",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
