# Generated by Django 5.2.15 on 2026-06-11 16:39

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RDTRZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("zone_code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("perumahan", "Perumahan"),
                            ("perdagangan", "Perdagangan & Jasa"),
                            ("industri", "Industri"),
                            ("pendidikan", "Sarana Pendidikan"),
                            ("kesehatan", "Sarana Kesehatan"),
                            ("perkantoran", "Perkantoran"),
                            ("campuran", "Campuran"),
                            ("rth", "Ruang Terbuka Hijau"),
                            ("transportasi", "Transportasi"),
                            ("pertanian", "Pertanian"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "bbox",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), default=list, size=4
                    ),
                ),
                ("geojson", models.JSONField(default=dict)),
                (
                    "allowed_sektors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), default=list, size=None
                    ),
                ),
                (
                    "allowed_kbli_codes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10), default=list, size=None
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, default="mock", max_length=100)),
            ],
            options={
                "ordering": ["zone_code"],
            },
        ),
        migrations.CreateModel(
            name="KBLICompatibility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kbli_code", models.CharField(db_index=True, max_length=10)),
                ("kbli_name", models.CharField(max_length=300)),
                ("is_compatible", models.BooleanField(default=True)),
                ("requires_special_permit", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kbli_compat",
                        to="rdtr.rdtrzone",
                    ),
                ),
            ],
            options={
                "ordering": ["kbli_code"],
                "unique_together": {("kbli_code", "zone")},
            },
        ),
    ]
